### ISSUE TITLE
在android6.0上崩溃

### ISSUE THREAD

**Issue by ndl1302732** [turing-technician/FastHook#12]
[
[crash.txt](https://github.com/turing-technician/FastHook/files/3144063/crash.txt)
](url)

**Comment by turing-technician** [comment]
callback分支只在8.1上做了测试，没有经过大量验证，可能会有一些版本不兼容的问题，后续解决

**Comment by turing-technician** [comment]
兼容了6.0，试试最新代码

**Comment by lulusudoku** [comment]
nexus6p android6.0上callback模式parseParam失败，setText的第一个参数parse为null，crash如下
`08-08 21:18:33.560 22291-22291/pers.turing.technician.fasthookapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: pers.turing.technician.fasthookapp, PID: 22291
    java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
        at pers.turing.technician.fasthookapp.MainActivity$10.beforeHookedMethod(MainActivity.java:220)
        at pers.turing.technician.fasthook.FastHookManager.hookHandle(FastHookManager.java:304)
        at pers.turing.technician.fasthook.FastHookManager.hookHandleVoid(FastHookManager.java:491)
        at pers.turing.technician.fasthookapp.MainActivity.reset(MainActivity.java:234)
        at pers.turing.technician.fasthookapp.MainActivity.test(MainActivity.java:244)
        at pers.turing.technician.fasthookapp.MainActivity$1.onClick(MainActivity.java:93)
        at android.view.View.performClick(View.java:5204)
        at android.view.View$PerformClick.run(View.java:21153)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`
